import asyncio
import json
import random
import logging
import websockets
from websockets.asyncio.server import serve

# Setup Logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

class LighthouseServer:
    def __init__(self):
        self.clients = {}  # ws -> client_info (dict)
        self.credentials_map = {}  # username (str) -> ws
        self.active_session = None  # Tuple of (controller_ws, host_ws) or None

    def generate_credentials(self):
        while True:
            # Generate 6 digit username formatted like '123456'
            part1 = random.randint(100, 999)
            part2 = random.randint(100, 999)
            username = f"{part1}{part2}"
            if username not in self.credentials_map:
                break
        # Generate 4 digit numeric password
        password = "".join(random.choices("0123456789", k=4))
        return username, password

    async def handle_connection(self, websocket, path=None):
        logging.info(f"New connection from {websocket.remote_address}")
        self.clients[websocket] = {
            "username": None,
            "password": None,
            "role": "idle",  # idle, host, controller
            "partner": None
        }

        try:
            async for message in websocket:
                if isinstance(message, bytes):
                    # Binary message relay (screen frame JPEG bytes)
                    partner = self.clients[websocket]["partner"]
                    if partner and self.active_session and (websocket in self.active_session):
                        try:
                            await partner.send(message)
                        except Exception as e:
                            logging.error(f"Error relaying binary data: {e}")
                else:
                    # Text message parsing (JSON)
                    try:
                        data = json.loads(message)
                    except json.JSONDecodeError:
                        logging.warning(f"Received invalid JSON: {message}")
                        continue

                    await self.process_message(websocket, data)

        except websockets.exceptions.ConnectionClosed:
            logging.info(f"Connection closed for {websocket.remote_address}")
        except Exception as e:
            logging.error(f"Error handling connection: {e}")
        finally:
            await self.cleanup_client(websocket)

    async def process_message(self, websocket, data):
        msg_type = data.get("type")
        client_info = self.clients[websocket]

        if msg_type == "register":
            # Host registers to get credentials generated by server
            username, password = self.generate_credentials()
            client_info["username"] = username
            client_info["password"] = password
            client_info["role"] = "host"
            self.credentials_map[username] = websocket
            logging.info(f"Registered host '{username}' with password '{password}'")
            
            await websocket.send(json.dumps({
                "type": "register_response",
                "username": username,
                "password": password
            }))

        elif msg_type == "connect_request":
            target_username = data.get("target_username")
            target_password = data.get("target_password")
            logging.info(f"Connection request to target '{target_username}' from {websocket.remote_address}")

            # 1-pair limitation check for the free version
            if self.active_session is not None:
                logging.info("Connection request rejected: Server busy.")
                await websocket.send(json.dumps({
                    "type": "connect_response",
                    "status": "error",
                    "message": "Server busy. Only 1 active session allowed in free version."
                }))
                return

            # Locate host client
            target_ws = self.credentials_map.get(target_username)
            if not target_ws or target_ws not in self.clients:
                await websocket.send(json.dumps({
                    "type": "connect_response",
                    "status": "error",
                    "message": "Remote user not found or offline."
                }))
                return

            target_info = self.clients[target_ws]
            if target_info["password"] != target_password:
                await websocket.send(json.dumps({
                    "type": "connect_response",
                    "status": "error",
                    "message": "Invalid remote password."
                }))
                return

            if target_info["role"] != "host" or target_info["partner"] is not None:
                await websocket.send(json.dumps({
                    "type": "connect_response",
                    "status": "error",
                    "message": "Remote user is currently busy."
                }))
                return

            # Pair them temporarily while awaiting permission approval
            client_info["role"] = "controller"
            client_info["partner"] = target_ws
            target_info["partner"] = websocket
            client_info["initial_quality"] = data.get("quality", "Medium")

            # Send permission request to host (Client B)
            logging.info(f"Asking permission from host '{target_username}'")
            await target_ws.send(json.dumps({
                "type": "permission_request",
                "from_username": client_info["username"] or "Remote User"
            }))

        elif msg_type == "permission_response":
            approved = data.get("approved", False)
            partner_ws = client_info["partner"]

            if not partner_ws or partner_ws not in self.clients:
                logging.warning("Host replied to permission request but partner went offline.")
                client_info["partner"] = None
                return

            partner_info = self.clients[partner_ws]

            if approved:
                # Double check if session got occupied while waiting
                if self.active_session is not None:
                    await partner_ws.send(json.dumps({
                        "type": "connect_response",
                        "status": "error",
                        "message": "Server became busy while waiting for permission."
                    }))
                    client_info["partner"] = None
                    partner_info["partner"] = None
                    partner_info["role"] = "idle"
                    return

                # Establish session (Controller, Host)
                self.active_session = (partner_ws, websocket)
                logging.info(f"Active session started: Controller={partner_ws.remote_address} <-> Host={websocket.remote_address}")

                await partner_ws.send(json.dumps({
                    "type": "connect_response",
                    "status": "approved"
                }))
                
                initial_quality = partner_info.get("initial_quality", "Medium")
                await websocket.send(json.dumps({
                    "type": "session_started",
                    "role": "host",
                    "quality": initial_quality
                }))
                await partner_ws.send(json.dumps({
                    "type": "session_started",
                    "role": "controller"
                }))
            else:
                logging.info(f"Host '{client_info['username']}' denied permission.")
                await partner_ws.send(json.dumps({
                    "type": "connect_response",
                    "status": "denied",
                    "message": "Permission request denied by the remote user."
                }))
                client_info["partner"] = None
                partner_info["partner"] = None
                partner_info["role"] = "idle"

        elif msg_type == "disconnect":
            logging.info(f"Disconnect requested by {websocket.remote_address}")
            await self.end_session(websocket, reason="Connection closed by user.")

        elif msg_type in ("input", "change_quality"):
            # Relay events/commands from controller to host
            partner = client_info["partner"]
            if partner and self.active_session and (websocket in self.active_session):
                try:
                    await partner.send(json.dumps(data))
                except Exception as e:
                    logging.error(f"Error relaying event ({msg_type}): {e}")

    async def end_session(self, websocket, reason="Session ended."):
        client_info = self.clients.get(websocket)
        if not client_info:
            return

        partner_ws = client_info["partner"]

        # Reset active session
        if self.active_session and (websocket in self.active_session or (partner_ws and partner_ws in self.active_session)):
            self.active_session = None

        # Reset client
        client_info["partner"] = None
        if client_info["role"] == "controller":
            client_info["role"] = "idle"

        # Reset partner and notify them
        if partner_ws and partner_ws in self.clients:
            partner_info = self.clients[partner_ws]
            partner_info["partner"] = None
            if partner_info["role"] == "controller":
                partner_info["role"] = "idle"
            try:
                await partner_ws.send(json.dumps({
                    "type": "session_ended",
                    "reason": reason
                }))
            except Exception:
                pass

        try:
            await websocket.send(json.dumps({
                "type": "session_ended",
                "reason": reason
            }))
        except Exception:
            pass

    async def cleanup_client(self, websocket):
        if websocket in self.clients:
            client_info = self.clients[websocket]
            username = client_info["username"]

            # Terminate active session if any
            await self.end_session(websocket, reason="Partner disconnected.")

            # Remove from credential maps
            if username and username in self.credentials_map:
                del self.credentials_map[username]

            del self.clients[websocket]
            logging.info(f"Cleaned up connection for {username or websocket.remote_address}")

async def main():
    import sys
    port = 8765
    if len(sys.argv) > 1:
        try:
            port = int(sys.argv[1])
        except ValueError:
            pass

    server = LighthouseServer()
    logging.info(f"Freeskoden Lighthouse coordination server listening on 0.0.0.0:{port}...")
    async with serve(server.handle_connection, "0.0.0.0", port):
        await asyncio.Future()  # run forever

if __name__ == "__main__":
    asyncio.run(main())
